# Generated by Django 2.2.5 on 2019-09-23 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
                ('text', models.TextField(max_length=3000)),
                ('user_ForeignKey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mem',
            },
        ),
        migrations.CreateModel(
            name='User_likes_mem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('mem_ForeignKey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='memes.Mem')),
                ('user_ForeignKey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_likes_mem',
            },
        ),
        migrations.CreateModel(
            name='Mem_in_q',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mem_ForeignKey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='memes.Mem')),
                ('user_ForeignKey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mem_in_q',
            },
        ),
    ]
