# Generated by Django 2.2.5 on 2019-09-29 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mem',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mem',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
