# Generated by Django 2.2.5 on 2019-10-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0002_auto_20190930_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='mem',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user_likes_mem',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
